# Generated by Django 4.2.10 on 2026-03-04 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivate job posting without deleting it'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_ats_score',
            field=models.FloatField(default=60, help_text='Minimum ATS score required to pass'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(help_text='Enter comma separated skills with weights (Example: Python:3, Django:2, SQL:1)'),
        ),
    ]
